### PR TITLE
Fix build for Coq v8.10

### PR DESCRIPTION
**Pull request by k4rtik**
I am unsure if my last commit is the best way to deal with deprecation: https://github.com/coq-contribs/semantics/commit/12b092708878bb93ef41e14649f20b511ee25613 but it works. Happy to learn about a better way to do this.

### CODE REVIEW

**Comment by herbelin** [comment]
Hi @k4rtik, thanks a lot for the PR. I can merge it as is, but, if you wish (and have some time for it), you could also replace each occurrence of names such as `Zmin` by its expansion such as `Z.min` (suspectingly without having to import `BinInt` explicitly, but I did not check).

**Comment by k4rtik** [comment]
Sure, I will take a look later tonight. I also wanted to get rid of some other warnings before this is merged.

**Comment by k4rtik** [comment]
Hi @herbelin, this should be ready to merge.  There are still some 4 unique warnings remaining, but that's all the time I had for this. Thanks for your help on Discourse and the suggestion here.

**Comment by herbelin** [comment]
Thanks!

**Pull request merged**
