### PR TITLE
Regenerate files from latest templates.

### PR DESCRIPTION
**Pull request by Zimmi48**
Includes a move from the Gitter badge to the Zulip badge in README.

### CODE REVIEW

**Comment by k4rtik** [comment]
Hi @Zimmi48 

Do you know where is the OPAM package build being maintained?

When I try to install using the opam instructions that you are adding in this PR, I receive this error:
```
$ opam install coq-semantics
The following dependencies couldn't be met:
  - coq-semantics → coq < 8.10~
      not available because the package is pinned to version 8.11.0
```
while this package certainly works well for 8.11.

I see the same issue with `hoare-tut` package (that I maintain). Perhaps the opam build source should be kept in the package's git repo or at least linked so it can be updated as well?

**Comment by Zimmi48** [comment]
Oh sorry @k4rtik, these are indeed the standard instructions but I didn't verify that they would work with your projects. The opam package definitions are maintained here: https://github.com/coq/opam-coq-archive. The package for coq-semantics was indeed not updated since 8.9: https://github.com/coq/opam-coq-archive/tree/master/released/packages/coq-semantics

>Perhaps the opam build source should be kept in the package's git repo or at least linked so it can be updated as well?

This can absolutely be done. In fact, the standard templates include an opam template.

**Comment by Zimmi48** [comment]
I've pushed an opam file in the PR. I see that there is also an extracted part. The usual practice is to have a second opam file about this extracted part. I'm less knowledgeable about this part but the keys to include in `meta.yml` are documented here:

https://github.com/coq-community/templates/blob/0c0aa1b0bbe6cec824e9bed769ad50f3e60e56b6/ref.yml#L247-L310

`@palmskog` may be able to help if you have questions.

PS: it is also good practice to have CI to ensure that this opam file is correct and that the project builds with the supported versions of Coq. This can also be added using the templates. Let me know if you'd like that.

**Comment by k4rtik** [comment]
> PS: it is also good practice to have CI to ensure that this opam file is correct and that the project builds with the supported versions of Coq. This can also be added using the templates. Let me know if you'd like that.

Yeah, I think it will be good to have that.

Does that also include some automation for sending new PRs to `opam-coq-archive` from one of these community projects from the source OPAM files? If not, I do not mind sending manual PRs when I ensure that the CI is happy.

Hi @palmskog, could you help with the extraction bit? I have only published [one OPAM package ever](https://opam.ocaml.org/packages/openQASM/), that too in OCaml. I do not see extraction-related info [in the previous OPAM file for v8.9](https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-semantics/coq-semantics.8.9.0/opam). Perhaps the default `make` build takes care of it as it does in source install here? If so, do we still need a second OPAM file?

**Comment by Zimmi48** [comment]
> Does that also include some automation for sending new PRs to `opam-coq-archive` from one of these community projects from the source OPAM files?

Unfortunately no, such automation is still on the roadmap but not available yet.

**Comment by Zimmi48** [comment]
I pushed a new commit setting up CI with GitHub Action. Unfortunately, it won't run until this is committed into the master branch (so I can't tell if CI is passing).

**Comment by k4rtik** [comment]
Thanks, I will test it later today by merging the commit.

Perhaps we can think about whether the second OPAM file is needed later. It doesn't seem included in previous packages either way.

**Pull request merged**
