### PR TITLE
Include new Coq versions in CI.

### PR DESCRIPTION
**Pull request by Zimmi48**
I noticed with #4 that currently the CI only tests Coq 8.10, 8.11 and master, which leaves a big gap. The main thing that this PR does is to fill it. The rest of the changes are mainly cosmetic to use the latest version of the coq-community templates.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Rebased on `master` to avoid the `Omega` issue. It seems that there is still an error in `master`:

```
   - File "./parser.v", line 78, characters 8-20:
  - Error:
  - In environment
  - a : ascii
  - The term "Z_of_ascii a" has type "Z" while it is expected to have type
  -  "String.string".
```

I'm interested in knowing whether this error is also present in 8.14 or not to figure out what the origin of the problem might be.

**Comment by Zimmi48** [comment]
So the new error is specific to Coq master / 8.15 (absent in Coq 8.14).

**Comment by Zimmi48** [comment]
OK, the issue is that https://github.com/coq/coq/pull/14234 introduced a new `?=` operator for strings, and thus Coq master interprets the `?=` in the following code as a different comparison function:

https://github.com/coq-community/semantics/blob/0f166c62a88a389a130ca9005124b9f1fff5e3b3/parser.v#L90-L108

I guess the fix is to open or close the right notation scopes, or to switch to an explicit call of the underlying `compare` function.

**Comment by k4rtik** [comment]
Thanks for the investigative work, I was looking into the same issue after removing omega in the [last commit](https://github.com/coq-community/semantics/commit/0f166c62a88a389a130ca9005124b9f1fff5e3b3). I will wait for your change.

**Comment by Zimmi48** [comment]
@k4rtik Sorry if I have given the impression a change was upcoming. I wanted to help debug what the issue was but was leaving it to you to decide what solution you wanted to implement here.

**Comment by k4rtik** [comment]
Sure, I can take it from here. You did go far beyond what I had in the investigation, so thanks so much!

**Comment by k4rtik** [comment]
Alright, the dev-version issue is resolved. Could you rebase to master again?

**Pull request merged**
